include::../locale/attributes.adoc[]
= Welcome to Jim's sandbox for dcat:DatasetSeries
:doctype: article
:docinfo: shared
:docinfodir: ../overview
:icons: font
:toc: left
:toclevels: 4
// :sectlinks:
:sectanchors:
:table-stripes: even
:xrefstyle: short

Let's play with dcat:DatasetSeries! 

We have the following three instances of dcat:Dataset, published by three different Agents: 

* https://jimjyang.github.io/playground/dataset-series/beesCZ2022[]: an open dataset as an instance of dcat:Dataset, published ny `Agent1`,
* https://jimjyang.github.io/playground/dataset-series/beesNL2022[]: an open dataset as an instance of dcat:Dataset, published by `Agent2`, 
* https://jimjyang.github.io/playground/dataset-series/beesNO2022[]: an open dataset as an instance of dcat:Dataset, published by `Agent3`.

We have the following file to be harvested into a certain data portal, created by `Agent4` who wants to create and publish a dataset series using the abovementioned three already published open datasets: 

* https://jimjyang.github.io/playground/dataset-series/source-for-harvesting[]

*Questions*: After the harvesting, should this instance of dcat:DatasetSeries be

. like https://jimjyang.github.io/playground/dataset-series/beesEU2022withMembers[]: an instance of dcat:DatasetSeries using dcat:seriesMembers referring to the abovementioned three instances of dcat:Dataset
.. Knowing that `Agent4` has no mandate to update the abovementioned three instances of dcat:Dataset, they will remain as they are. Without updating those instances of dcat:Dataset, is this implementation compliant with w3C/DCAT (when it uses only dcat:seriesMember without at the same using dcat:inSeries)?
. or like https://jimjyang.github.io/playground/dataset-series/beesEU2022withoutMembers[]: an instance of dcat:DatasetSeries _without_ using dcat:seriesMembers. 
.. Neither this instance of dcat:DatasetSeries nor the three instances of dcat:Dataset say anything about memberships of this new dataset series, how to know which datasets are in this dataset series? 
