== Om spesifikasjonen [[OmSpesifikasjonen]]

=== Formål [[Formål]]

//:xrefstyle: pass:[%n %t]
:xrefstyle: full

Formålet med spesifikasjonen er å legge til rette for en felles måte å beskrive "arkitekturartefakter", og en felles måte å utveksle beskrivelsene.  

_#@@@@@@ mer tekst kommer ...#_ 

=== Omfang og avgrensing [[Omfang-og-avgrensing]]

Spesifikasjonen er basert på EUs https://www.w3.org/TR/vocab-adms/[__Asset Description Metadata Schema (ADMS)__ &#x29C9;, window="_blank", role="ext-link"]. Spesifikasjonen gjenbruker også https://htmlpreview.github.io/?https://github.com/AlbertoDMendoza/archimate_ontology/blob/main/archimate.html[__ArchiMate Ontology__ &#x29C9;, window="_blank", role="ext-link"].

Spesifikasjonen inneholder også engelske navn (_English name_) og beskrivelser (_Usage note_). Det gjøres oppmerksom på at ikke alle engelske navn eller beskrivelser er ordrette sitater fra originale engelske tekster. Vi kan ha valgt en annen tekst til å formidle det samme budskapet på, med mindre vi eksplisitt sier at det er et avvik (dvs. også i meningsinnholdet). 

Ettersom spesifikasjonen er basert på https://www.w3.org/RDF/[Resource Description Framework (RDF). &#x29C9;, window="_blank", role="ext-link"], vil beskrivelsene i henhold til spesifikasjonen også være RDF-baserte og dermed maskinprosesserbare. Som støtte til teknisk implementering er det i spesifikasjonen også tatt med en del eksempler i RDF Turtle. Eksemplene i RDF Turtle er kun veiledende, de er ikke komplette og kan også mangle verdier til obligatoriske egenskaper.

=== Målgrupper [[Målgrupper]]

_#@@@@@@ mer tekst kommer ...#_
 

=== Forvaltningsregime [[Forvaltningsregime]]

Spesifikasjonen forvaltes av https://digdir.no[Digitaliseringsdirektoratet (Digdir) &#x29C9;, window="_blank", role="ext-link"].

_#@@@@@@ mer tekst kommer ...#_

=== Om kravnivåene i spesifikasjonen [[Om-kravnivåene]]

Spesifikasjonen bruker ordene «obligatorisk» ("_mandatory_"), «anbefalt» ("_recommended_") og «valgfri» ("_optional_"). Disse er https://data.norge.no/specification/dcat-ap-no/#Om-kravene[forklart i DCAT-AP-NO &#x29C9;, window="_blank", role="ext-link"], og forklaringene gjentas ikke her.

