include::../locale/attributes.adoc[]
= Generering av RDF Turtle med HTML-visning
:doctype: article
:docinfo: shared
:docinfodir: ../overview
:icons: font
:toc: left
:toclevels: 4
// :sectlinks:
:sectanchors:
:table-stripes: even
:xrefstyle: short

Velkommen til sandkassa for Excel-verktøyet som automatisk genererer RDF Turtle og Asciidoc (for HTML-generering)!

== Hensikt 

For å dekke behovet for generering av RDF Turtle-representasjon i henhold til en gitt RDF-basert spesifikasjon, og samtidig å kunne ha en menneskevennlig visning av RDF Turtle-innholdet, laget jeg et Excel-verktøy som ut fra en mal automatisk genererer RDF Turtle og Asciidoc (for HTML-generering).

Jeg har laget Excel-maler for følgende RDF-baserte spesifikasjoner: 

* https://informasjonsforvaltning.github.io/cpsv-ap-no/[CPSV-AP-NO  &#x29C9;, window="_blank", role="ext-link"]
* https://data.norge.no/specification/dcat-ap-no[DCAT-AP-NO  &#x29C9;, window="_blank", role="ext-link"]
* https://data.norge.no/specification/modelldcat-ap-no[ModellDCAT-AP-NO  &#x29C9;, window="_blank", role="ext-link"]
* https://data.norge.no/specification/skos-ap-no-begrep[SKOS-AP-NO-Begrep  &#x29C9;, window="_blank", role="ext-link"]
* https://data.norge.no/specification/xkos-ap-no[XKOS-AP-NO  &#x29C9;, window="_blank", role="ext-link"]

Verktøyet er også laget med sikte på å kunne brukes til å sette opp mal for generering av RDF Turtle generelt, med HTML-visning. 

Verktøyet legges ikke  ut her ettersom det inneholder makroer. Du som er kommet til denne siden skal som regel kjenne meg slik at du vet hvordan du kan ta kontakt med meg hvis du har behov for dette verktøyet. 

== Brukerveiledning

Det har ikke vært et mål å lage et robust verktøy, men verktøyet skal kunne fungere ved «normal» bruk. Her er en link:user-guide[enkel brukerveiledning] som forklarer hva som er «normal» bruk. 

== Forbehold

Det er ingen garanti for at verktøyet vil kunne fungere i alle tilfeller, heller ikke at malene er/blir oppdatert i takt med ev. oppdateringer av spesifikasjonene nevnt ovenfor. Din virksomhets interne sikkerhetspolicy kan også sperre for bruk av makroer.   
