name: Deploy xkosno to Github Pages

on:
  push:
    branches:
      - main
    paths:
      - xkosno/**
  workflow_dispatch:

jobs:
  adoc_build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    name: deploy from xkosno to GH-pages
    steps:

    - name: Checkout code
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0

    - name: Build html
      id: adocbuild_html
      uses: Analog-inc/asciidoctor-action@328aa83fd20efb2e8899a34716db60c9ddf2d9a0  # master
      with:
         shellcommand: "asciidoctor -D xkosno -o index.html -a lang=en xkosno/main.adoc"

    - name: Deploy
      if: github.event_name != 'workflow_dispatch' || github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@84c30a85c19949d7eee79c4ff27748b70285e453
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./xkosno
        destination_dir: ./xkosno
        keep_files: true
