name: Build adocs and deploy from overview to Github Pages

on:
  push:
    branches:
      - main
    paths:
      - overview/**
  workflow_dispatch:

jobs:
  adoc_build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    name: asciidoctor build
    steps:

    - name: Checkout code
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

    - name: Build html
      id: adocbuild_html
      uses: Analog-inc/asciidoctor-action@328aa83fd20efb2e8899a34716db60c9ddf2d9a0  # master
      with:
          shellcommand: "asciidoctor -D overview -o index.html -a lang=en overview/main.adoc"

    - name: Deploy
      if: github.event_name != 'workflow_dispatch' || github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@84c30a85c19949d7eee79c4ff27748b70285e453
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./overview
        keep_files: true
