name: Build adocs and deploy archadms-ap-no to Github Pages

permissions:
  contents: write

on:
  push:
    branches:
    - main
    paths:
    - archadms-ap-no/docs/**

jobs:
  build-adocs:
    uses: Informasjonsforvaltning/workflows/.github/workflows/specification-github-pages.yaml@main
    with:
      program_html: |
        asciidoctor -D archadms-ap-no/docs -o index.html -a lang=nb archadms-ap-no/docs/main.adoc
      program_pdf: |
        asciidoctor-pdf -D archadms-ap-no/docs -o files/archadms-ap-no.pdf -a lang=nb archadms-ap-no/docs/main.adoc
      publish_branch: gh-pages
      publish_dir: ./archadms-ap-no/docs/
      destination_dir: ./archadms-ap-no/
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}