name: Build adocs and deploy archadms-ap-no to Github Pages

permissions:
  contents: write
  pages: write

on:
  push:
    branches:
    - main
    paths:
    - archadms-ap-no/docs/**
  workflow_dispatch:

jobs:
  adoc_build:
    runs-on: ubuntu-latest
    name: deploy from archadms-ap-no/docs to GH-pages
    steps:

    - name: Checkout code
      uses: actions/checkout@v6

    - name: Build html 
      id: adocbuild_html
      uses: tonynv/asciidoctor-action@master
      with:
            program: "asciidoctor -D archadms-ap-no/docs -o index.html -a lang=nb archadms-ap-no/docs/main.adoc"

    - name: Build pdf
      id: adocbuild_pdf
      uses: tonynv/asciidoctor-action@master
      with:
          program: "asciidoctor-pdf -D archadms-ap-no/docs -o files/archadms-ap-no.pdf -a lang=nb archadms-ap-no/docs/main.adoc"
      continue-on-error: true

    - name: Deploy to Github-Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./archadms-ap-no/docs/
        destination_dir: ./archadms-ap-no/
