name: Build adocs and deploy dataset-series to Github Pages

on:
  push:
    branches:
    - main
    paths:
    - dataset-series/**
  workflow_dispatch:

jobs:
  adoc_build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    name: deploy from dataset-series to GH-pages
    steps:

    - name: Checkout code
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

    - name: Build html 
      id: adocbuild_html
      uses: Analog-inc/asciidoctor-action@master
      with:
            shellcommand: "asciidoctor -D dataset-series -o index.html -a lang=en dataset-series/main.adoc"

    - name: Deploy to Github-Pages
      if: github.event_name != 'workflow_dispatch' || github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@84c30a85c19949d7eee79c4ff27748b70285e453
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./dataset-series
        destination_dir: ./dataset-series
        keep_files: true
