name: Build adocs and deploy dataset-series to Github Pages

on:
  push:
    branches:
    - main
    paths:
    - dataset-series/**
  workflow_dispatch:

jobs:
  adoc_build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    name: deploy from dataset-series to GH-pages
    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build html 
      id: adocbuild_html
      uses: tonynv/asciidoctor-action@master
      with:
            program: "asciidoctor -D dataset-series -o index.html -a lang=en dataset-series/main.adoc"

    - name: Deploy to Github-Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./dataset-series
        destination_dir: ./dataset-series
        keep_files: true
