name: Build adocs and deploy excel2turtle-n-adoc to Github Pages

on:
  push:
    branches:
    - main
    paths:
    - excel2turtle-n-adoc/**
  workflow_dispatch:

jobs:
  adoc_build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    name: asciidoctor build
    steps:

    - name: Checkout code
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

    - name: Build html - intro
      id: adocbuild_html_intro
      uses: Analog-inc/asciidoctor-action@master
      with:
          shellcommand: "asciidoctor -D excel2turtle-n-adoc -o index.html -a lang=nb excel2turtle-n-adoc/main.adoc"

    - name: Build html - user guide
      id: adocbuild_html_userguide
      uses: Analog-inc/asciidoctor-action@master
      with:
         shellcommand: "asciidoctor -D excel2turtle-n-adoc/user-guide -o index.html -a lang=nb excel2turtle-n-adoc/user-guide-main.adoc"

    - name: Deploy
      uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: excel2turtle-n-adoc
        destination_dir: ./xls2ttl&adoc
        keep_files: true
