name: Deploy fixed textbox to Github Pages

on:
  push:
    branches:
      - main
    paths:
      - test-fixed-textbox/**
  workflow_dispatch:

jobs:
  adoc_build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    name: deploy from test-fixed-textbox to GH-pages
    steps:

    - name: Checkout code
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10

    - name: Deploy
      if: github.event_name != 'workflow_dispatch' || github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@84c30a85c19949d7eee79c4ff27748b70285e453
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./test-fixed-textbox
        destination_dir: ./test-fixed-textbox
        keep_files: true
